### ISSUE TITLE
More detail for RODBC vs dplyr::tbl syntax and connection setup 

### ISSUE THREAD

**Issue by jen-machin** [dfe-analytical-services/techskills_workshops#17]
The connection setup for both is different and can result in [this error](https://stackoverflow.com/questions/52721747/first-argument-is-not-an-open-rodbc-channel). Do we need to explain connection settings in more detail so that people can just copy/paste syntax? Could probably use headings for option 1 and option 2 descriptions too to make them a bit clearer.

**Comment by jen-machin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Look through issues in R workshop docs and decide which to fix](https://trello.com/c/ZWLZcUfH/1155-look-through-issues-in-r-workshop-docs-and-decide-which-to-fix)

**Comment by rmbielby** [comment]
RODBC::sqlQuery() lacks a connection set-up, so people are trying to use the DBI connection to run it. Could move the whole RODBC thing to a separate footnote or appendix?
